"""Reusable quantitative finance functions for the course notebooks."""

from .options import black_scholes_call, implied_volatility
from .options import (
    black_scholes_put,
    binomial_american,
    binomial_european,
    finite_difference_delta,
    finite_difference_gamma,
    implied_volatility_bisection,
    implied_volatility_newton,
    monte_carlo_european_option,
)
from .numerical import bisection, cubic_spline_curve, linear_interpolation, newton_raphson
from .performance import (
    certainty_equivalent,
    information_ratio,
    kappa_ratio,
    lower_partial_moment,
    omega_ratio,
    sharpe_ratio,
    sortino_ratio,
    treynor_ratio,
)
from .portfolio import (
    capm_expected_return,
    efficient_frontier,
    estimate_capm,
    global_minimum_variance,
    gmv_weights,
    jensen_alpha,
    minimum_variance_target_return,
    portfolio_sharpe,
    portfolio_variance,
    portfolio_volatility,
    tangency_portfolio,
)
from .returns import log_return, pnl_long, pnl_short, portfolio_return, simple_return
from .fixed_income import (
    continuous_compounding,
    convexity,
    future_value,
    macaulay_duration,
    modified_duration,
    present_value,
)
from .linear_algebra import (
    PCAResult,
    cholesky_correlated_samples,
    correlation_to_covariance,
    covariance_to_correlation,
    is_positive_definite,
    nearest_valid_covariance,
    pca_from_correlation,
    pca_from_covariance,
)
from .statistics import (
    descriptive_statistics,
    fit_normal_mle,
    fit_student_t,
    historical_quantile,
    normal_log_likelihood,
)
from .simulation import (
    simulate_correlated_normal,
    simulate_gbm,
    simulate_jump_diffusion,
    simulate_multivariate_student_t,
    simulate_ou,
    simulate_random_walk,
)
from .regression import (
    OLSResult,
    calculate_vif,
    capm_regression,
    minimum_variance_hedge_ratio,
    ols_numpy,
    regression_diagnostics,
)

__all__ = [
    "black_scholes_call",
    "black_scholes_put",
    "bisection",
    "binomial_american",
    "binomial_european",
    "cholesky_correlated_samples",
    "certainty_equivalent",
    "capm_expected_return",
    "continuous_compounding",
    "cubic_spline_curve",
    "correlation_to_covariance",
    "covariance_to_correlation",
    "convexity",
    "future_value",
    "efficient_frontier",
    "estimate_capm",
    "finite_difference_delta",
    "finite_difference_gamma",
    "gmv_weights",
    "global_minimum_variance",
    "implied_volatility",
    "implied_volatility_bisection",
    "implied_volatility_newton",
    "information_ratio",
    "kappa_ratio",
    "lower_partial_moment",
    "jensen_alpha",
    "log_return",
    "macaulay_duration",
    "modified_duration",
    "omega_ratio",
    "portfolio_variance",
    "portfolio_return",
    "pnl_long",
    "pnl_short",
    "portfolio_volatility",
    "portfolio_sharpe",
    "present_value",
    "is_positive_definite",
    "nearest_valid_covariance",
    "PCAResult",
    "pca_from_correlation",
    "pca_from_covariance",
    "descriptive_statistics",
    "fit_normal_mle",
    "fit_student_t",
    "historical_quantile",
    "normal_log_likelihood",
    "linear_interpolation",
    "monte_carlo_european_option",
    "newton_raphson",
    "OLSResult",
    "ols_numpy",
    "regression_diagnostics",
    "calculate_vif",
    "capm_regression",
    "minimum_variance_hedge_ratio",
    "simulate_gbm",
    "simulate_jump_diffusion",
    "simulate_correlated_normal",
    "simulate_multivariate_student_t",
    "simulate_ou",
    "simulate_random_walk",
    "tangency_portfolio",
    "minimum_variance_target_return",
    "treynor_ratio",
    "sharpe_ratio",
    "simple_return",
    "sortino_ratio",
]
